/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
// import org.threeten.bp.OffsetDateTime;
/**
 * CalculatedGoodTaxPayload
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-02T14:34:29.121+02:00[Europe/Kiev]")
public class CalculatedGoodTaxPayload {
  @SerializedName("code")
  private Integer code = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("rate")
  private BigDecimal rate = null;

  @SerializedName("value")
  private BigDecimal value = null;

  @SerializedName("extra_rate")
  private BigDecimal extraRate = null;

  @SerializedName("extra_value")
  private BigDecimal extraValue = null;

  @SerializedName("included")
  private Boolean included = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  public CalculatedGoodTaxPayload code(Integer code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(required = true, description = "")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public CalculatedGoodTaxPayload label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @Schema(required = true, description = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public CalculatedGoodTaxPayload symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @Schema(required = true, description = "")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public CalculatedGoodTaxPayload rate(BigDecimal rate) {
    this.rate = rate;
    return this;
  }

   /**
   * Get rate
   * @return rate
  **/
  @Schema(required = true, description = "")
  public BigDecimal getRate() {
    return rate;
  }

  public void setRate(BigDecimal rate) {
    this.rate = rate;
  }

  public CalculatedGoodTaxPayload value(BigDecimal value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @Schema(required = true, description = "")
  public BigDecimal getValue() {
    return value;
  }

  public void setValue(BigDecimal value) {
    this.value = value;
  }

  public CalculatedGoodTaxPayload extraRate(BigDecimal extraRate) {
    this.extraRate = extraRate;
    return this;
  }

   /**
   * Get extraRate
   * @return extraRate
  **/
  @Schema(description = "")
  public BigDecimal getExtraRate() {
    return extraRate;
  }

  public void setExtraRate(BigDecimal extraRate) {
    this.extraRate = extraRate;
  }

  public CalculatedGoodTaxPayload extraValue(BigDecimal extraValue) {
    this.extraValue = extraValue;
    return this;
  }

   /**
   * Get extraValue
   * @return extraValue
  **/
  @Schema(required = true, description = "")
  public BigDecimal getExtraValue() {
    return extraValue;
  }

  public void setExtraValue(BigDecimal extraValue) {
    this.extraValue = extraValue;
  }

  public CalculatedGoodTaxPayload included(Boolean included) {
    this.included = included;
    return this;
  }

   /**
   * Get included
   * @return included
  **/
  @Schema(required = true, description = "")
  public Boolean isIncluded() {
    return included;
  }

  public void setIncluded(Boolean included) {
    this.included = included;
  }

  public CalculatedGoodTaxPayload createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CalculatedGoodTaxPayload calculatedGoodTaxPayload = (CalculatedGoodTaxPayload) o;
    return Objects.equals(this.code, calculatedGoodTaxPayload.code) &&
        Objects.equals(this.label, calculatedGoodTaxPayload.label) &&
        Objects.equals(this.symbol, calculatedGoodTaxPayload.symbol) &&
        Objects.equals(this.rate, calculatedGoodTaxPayload.rate) &&
        Objects.equals(this.value, calculatedGoodTaxPayload.value) &&
        Objects.equals(this.extraRate, calculatedGoodTaxPayload.extraRate) &&
        Objects.equals(this.extraValue, calculatedGoodTaxPayload.extraValue) &&
        Objects.equals(this.included, calculatedGoodTaxPayload.included) &&
        Objects.equals(this.createdAt, calculatedGoodTaxPayload.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, label, symbol, rate, value, extraRate, extraValue, included, createdAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CalculatedGoodTaxPayload {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    extraRate: ").append(toIndentedString(extraRate)).append("\n");
    sb.append("    extraValue: ").append(toIndentedString(extraValue)).append("\n");
    sb.append("    included: ").append(toIndentedString(included)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
