/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * CashPaymentPayload
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-02T14:34:29.121+02:00[Europe/Kiev]")
public class CashPaymentPayload implements AnyOfCalculatedReceiptSellPayloadPaymentsItems, AnyOfOfflineReceiptSellPayloadPaymentsItems, AnyOfOrderReceiptModelPaymentsItems, AnyOfReceiptModelPaymentsItems, AnyOfReceiptSellPayloadPaymentsItems, AnyOfReceiptServicePayloadPayment, AnyOfShortReceiptModelPaymentsItems {
  @SerializedName("type")
  private PaymentType type = PaymentType.CASH;

  @SerializedName("pawnshop_is_return")
  private Boolean pawnshopIsReturn = null;

  @SerializedName("value")
  private Integer value = null;

  @SerializedName("label")
  private String label = "Готівка";

  public CashPaymentPayload type(PaymentType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public PaymentType getType() {
    return type;
  }

  public void setType(PaymentType type) {
    this.type = type;
  }

  public CashPaymentPayload pawnshopIsReturn(Boolean pawnshopIsReturn) {
    this.pawnshopIsReturn = pawnshopIsReturn;
    return this;
  }

   /**
   * Get pawnshopIsReturn
   * @return pawnshopIsReturn
  **/
  @Schema(description = "")
  public Boolean isPawnshopIsReturn() {
    return pawnshopIsReturn;
  }

  public void setPawnshopIsReturn(Boolean pawnshopIsReturn) {
    this.pawnshopIsReturn = pawnshopIsReturn;
  }

  public CashPaymentPayload value(Integer value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @Schema(required = true, description = "")
  public Integer getValue() {
    return value;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public CashPaymentPayload label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @Schema(description = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CashPaymentPayload cashPaymentPayload = (CashPaymentPayload) o;
    return Objects.equals(this.type, cashPaymentPayload.type) &&
        Objects.equals(this.pawnshopIsReturn, cashPaymentPayload.pawnshopIsReturn) &&
        Objects.equals(this.value, cashPaymentPayload.value) &&
        Objects.equals(this.label, cashPaymentPayload.label);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, pawnshopIsReturn, value, label);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CashPaymentPayload {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    pawnshopIsReturn: ").append(toIndentedString(pawnshopIsReturn)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
