/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.v3.oas.annotations.media.Schema;
import ua.checkbox.j8client.model.CashRegisterOfflineTimeSession;
import ua.checkbox.j8client.model.CashRegisterOfflineTimeStatus;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * CashRegisterOfflineTime
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-02T14:34:29.121+02:00[Europe/Kiev]")
public class CashRegisterOfflineTime {
  @SerializedName("status")
  private CashRegisterOfflineTimeStatus status = null;

  @SerializedName("sessions")
  private List<CashRegisterOfflineTimeSession> sessions = null;

  public CashRegisterOfflineTime status(CashRegisterOfflineTimeStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public CashRegisterOfflineTimeStatus getStatus() {
    return status;
  }

  public void setStatus(CashRegisterOfflineTimeStatus status) {
    this.status = status;
  }

  public CashRegisterOfflineTime sessions(List<CashRegisterOfflineTimeSession> sessions) {
    this.sessions = sessions;
    return this;
  }

  public CashRegisterOfflineTime addSessionsItem(CashRegisterOfflineTimeSession sessionsItem) {
    if (this.sessions == null) {
      this.sessions = new ArrayList<CashRegisterOfflineTimeSession>();
    }
    this.sessions.add(sessionsItem);
    return this;
  }

   /**
   * Get sessions
   * @return sessions
  **/
  @Schema(description = "")
  public List<CashRegisterOfflineTimeSession> getSessions() {
    return sessions;
  }

  public void setSessions(List<CashRegisterOfflineTimeSession> sessions) {
    this.sessions = sessions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CashRegisterOfflineTime cashRegisterOfflineTime = (CashRegisterOfflineTime) o;
    return Objects.equals(this.status, cashRegisterOfflineTime.status) &&
        Objects.equals(this.sessions, cashRegisterOfflineTime.sessions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, sessions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CashRegisterOfflineTime {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    sessions: ").append(toIndentedString(sessions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
