/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.v3.oas.annotations.media.Schema;
import ua.checkbox.j8client.model.OrderReceiptModel;

import java.io.IOException;
import java.util.UUID;
/**
 * CreateOrderModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-02T14:34:29.121+02:00[Europe/Kiev]")
public class CreateOrderModel implements AnyOfOrdersModel {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("order_id")
  private String orderId = null;

  @SerializedName("receipt_draft")
  private OrderReceiptModel receiptDraft = null;

  public CreateOrderModel id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public CreateOrderModel orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  @Schema(description = "")
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public CreateOrderModel receiptDraft(OrderReceiptModel receiptDraft) {
    this.receiptDraft = receiptDraft;
    return this;
  }

   /**
   * Get receiptDraft
   * @return receiptDraft
  **/
  @Schema(required = true, description = "")
  public OrderReceiptModel getReceiptDraft() {
    return receiptDraft;
  }

  public void setReceiptDraft(OrderReceiptModel receiptDraft) {
    this.receiptDraft = receiptDraft;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateOrderModel createOrderModel = (CreateOrderModel) o;
    return Objects.equals(this.id, createOrderModel.id) &&
        Objects.equals(this.orderId, createOrderModel.orderId) &&
        Objects.equals(this.receiptDraft, createOrderModel.receiptDraft);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, orderId, receiptDraft);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateOrderModel {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    receiptDraft: ").append(toIndentedString(receiptDraft)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
