/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
// import org.threeten.bp.OffsetDateTime;
/**
 * CurrencyRateModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-02T14:34:29.121+02:00[Europe/Kiev]")
public class CurrencyRateModel {
  @SerializedName("code")
  private String code = null;

  @SerializedName("symbol_code")
  private String symbolCode = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("sell")
  private BigDecimal sell = null;

  @SerializedName("buy")
  private BigDecimal buy = null;

  @SerializedName("regulator")
  private BigDecimal regulator = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  @SerializedName("updated_at")
  private OffsetDateTime updatedAt = null;

  @SerializedName("active")
  private Boolean active = null;

  @SerializedName("sell_sum")
  private Integer sellSum = 0;

  @SerializedName("buy_sum")
  private Integer buySum = 0;

  public CurrencyRateModel code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(required = true, description = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public CurrencyRateModel symbolCode(String symbolCode) {
    this.symbolCode = symbolCode;
    return this;
  }

   /**
   * Get symbolCode
   * @return symbolCode
  **/
  @Schema(required = true, description = "")
  public String getSymbolCode() {
    return symbolCode;
  }

  public void setSymbolCode(String symbolCode) {
    this.symbolCode = symbolCode;
  }

  public CurrencyRateModel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CurrencyRateModel sell(BigDecimal sell) {
    this.sell = sell;
    return this;
  }

   /**
   * Get sell
   * @return sell
  **/
  @Schema(required = true, description = "")
  public BigDecimal getSell() {
    return sell;
  }

  public void setSell(BigDecimal sell) {
    this.sell = sell;
  }

  public CurrencyRateModel buy(BigDecimal buy) {
    this.buy = buy;
    return this;
  }

   /**
   * Get buy
   * @return buy
  **/
  @Schema(required = true, description = "")
  public BigDecimal getBuy() {
    return buy;
  }

  public void setBuy(BigDecimal buy) {
    this.buy = buy;
  }

  public CurrencyRateModel regulator(BigDecimal regulator) {
    this.regulator = regulator;
    return this;
  }

   /**
   * Get regulator
   * @return regulator
  **/
  @Schema(required = true, description = "")
  public BigDecimal getRegulator() {
    return regulator;
  }

  public void setRegulator(BigDecimal regulator) {
    this.regulator = regulator;
  }

  public CurrencyRateModel createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public CurrencyRateModel updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @Schema(description = "")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public CurrencyRateModel active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @Schema(required = true, description = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public CurrencyRateModel sellSum(Integer sellSum) {
    this.sellSum = sellSum;
    return this;
  }

   /**
   * Get sellSum
   * @return sellSum
  **/
  @Schema(description = "")
  public Integer getSellSum() {
    return sellSum;
  }

  public void setSellSum(Integer sellSum) {
    this.sellSum = sellSum;
  }

  public CurrencyRateModel buySum(Integer buySum) {
    this.buySum = buySum;
    return this;
  }

   /**
   * Get buySum
   * @return buySum
  **/
  @Schema(description = "")
  public Integer getBuySum() {
    return buySum;
  }

  public void setBuySum(Integer buySum) {
    this.buySum = buySum;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CurrencyRateModel currencyRateModel = (CurrencyRateModel) o;
    return Objects.equals(this.code, currencyRateModel.code) &&
        Objects.equals(this.symbolCode, currencyRateModel.symbolCode) &&
        Objects.equals(this.name, currencyRateModel.name) &&
        Objects.equals(this.sell, currencyRateModel.sell) &&
        Objects.equals(this.buy, currencyRateModel.buy) &&
        Objects.equals(this.regulator, currencyRateModel.regulator) &&
        Objects.equals(this.createdAt, currencyRateModel.createdAt) &&
        Objects.equals(this.updatedAt, currencyRateModel.updatedAt) &&
        Objects.equals(this.active, currencyRateModel.active) &&
        Objects.equals(this.sellSum, currencyRateModel.sellSum) &&
        Objects.equals(this.buySum, currencyRateModel.buySum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, symbolCode, name, sell, buy, regulator, createdAt, updatedAt, active, sellSum, buySum);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CurrencyRateModel {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    symbolCode: ").append(toIndentedString(symbolCode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    sell: ").append(toIndentedString(sell)).append("\n");
    sb.append("    buy: ").append(toIndentedString(buy)).append("\n");
    sb.append("    regulator: ").append(toIndentedString(regulator)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    sellSum: ").append(toIndentedString(sellSum)).append("\n");
    sb.append("    buySum: ").append(toIndentedString(buySum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
