/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import java.util.List;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * DiscountPayload
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-02T14:34:29.121+02:00[Europe/Kiev]")
public class DiscountPayload {
  @SerializedName("type")
  private DiscountType type = null;

  @SerializedName("mode")
  private DiscountMode mode = null;

  @SerializedName("value")
  private int value = 0;

  @SerializedName("tax_code")
  private AnyOfDiscountPayloadTaxCode taxCode = null;

  @SerializedName("tax_codes")
  private List<Integer> taxCodes;

  @SerializedName("name")
  private String name = null;

  public DiscountPayload type(DiscountType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(required = true, description = "")
  public DiscountType getType() {
    return type;
  }

  public void setType(DiscountType type) {
    this.type = type;
  }

  public DiscountPayload mode(DiscountMode mode) {
    this.mode = mode;
    return this;
  }

   /**
   * Get mode
   * @return mode
  **/
  @Schema(required = true, description = "")
  public DiscountMode getMode() {
    return mode;
  }

  public void setMode(DiscountMode mode) {
    this.mode = mode;
  }

  public DiscountPayload value(int i) {
    this.value = i;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @Schema(required = true, description = "")
  public int getValue() {
    return value;
  }

  public void setValue(int value) {
    this.value = value;
  }

  public DiscountPayload taxCode(AnyOfDiscountPayloadTaxCode taxCode) {
    this.taxCode = taxCode;
    return this;
  }

   /**
   * Get taxCode
   * @return taxCode
  **/
  @Schema(description = "")
  public AnyOfDiscountPayloadTaxCode getTaxCode() {
    return taxCode;
  }

  public void setTaxCode(AnyOfDiscountPayloadTaxCode taxCode) {
    this.taxCode = taxCode;
  }

  public DiscountPayload taxCodes(List<Integer> taxCodes) {
    this.taxCodes = taxCodes;
    return this;
  }

   /**
   * Get taxCodes
   * @return taxCodes
  **/
  @Schema(description = "")
  public List<Integer> getTaxCodes() {
    return taxCodes;
  }

  public void setTaxCodes(List<Integer> taxCodes) {
    this.taxCodes = taxCodes;
  }

  public DiscountPayload name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiscountPayload discountPayload = (DiscountPayload) o;
    return Objects.equals(this.type, discountPayload.type) &&
        Objects.equals(this.mode, discountPayload.mode) &&
        Objects.equals(this.value, discountPayload.value) &&
        Objects.equals(this.taxCode, discountPayload.taxCode) &&
        Objects.equals(this.taxCodes, discountPayload.taxCodes) &&
        Objects.equals(this.name, discountPayload.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, mode, value, taxCode, taxCodes, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiscountPayload {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    taxCode: ").append(toIndentedString(taxCode)).append("\n");
    sb.append("    taxCodes: ").append(toIndentedString(taxCodes)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
