/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.List;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * DiscountModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-02T14:34:29.121+02:00[Europe/Kiev]")
public class DiscountModel {
  @SerializedName("type")
  private DiscountType type = null;

  @SerializedName("mode")
  private DiscountMode mode = null;

  @SerializedName("value")
  private BigDecimal value = null;

  @SerializedName("tax_code")
  private AnyOfDiscountModelTaxCode taxCode = null;

  @SerializedName("tax_codes")
  private List<Integer> taxCodes = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("sum")
  private Integer sum = null;

  public DiscountModel type(DiscountType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(required = true, description = "")
  public DiscountType getType() {
    return type;
  }

  public void setType(DiscountType type) {
    this.type = type;
  }

  public DiscountModel mode(DiscountMode mode) {
    this.mode = mode;
    return this;
  }

   /**
   * Get mode
   * @return mode
  **/
  @Schema(required = true, description = "")
  public DiscountMode getMode() {
    return mode;
  }

  public void setMode(DiscountMode mode) {
    this.mode = mode;
  }

  public DiscountModel value(BigDecimal value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @Schema(required = true, description = "")
  public BigDecimal getValue() {
    return value;
  }

  public void setValue(BigDecimal value) {
    this.value = value;
  }

  public DiscountModel taxCode(AnyOfDiscountModelTaxCode taxCode) {
    this.taxCode = taxCode;
    return this;
  }

   /**
   * Get taxCode
   * @return taxCode
  **/
  @Schema(description = "")
  public AnyOfDiscountModelTaxCode getTaxCode() {
    return taxCode;
  }

  public void setTaxCode(AnyOfDiscountModelTaxCode taxCode) {
    this.taxCode = taxCode;
  }

  public DiscountModel taxCodes(List<Integer> taxCodes) {
    this.taxCodes = taxCodes;
    return this;
  }

   /**
   * Get taxCodes
   * @return taxCodes
  **/
  @Schema(description = "")
  public List<Integer>  getTaxCodes() {
    return taxCodes;
  }

  public void setTaxCodes(List<Integer> taxCodes) {
    this.taxCodes = taxCodes;
  }

  public DiscountModel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DiscountModel sum(Integer sum) {
    this.sum = sum;
    return this;
  }

   /**
   * Get sum
   * @return sum
  **/
  @Schema(required = true, description = "")
  public Integer getSum() {
    return sum;
  }

  public void setSum(Integer sum) {
    this.sum = sum;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiscountModel discountModel = (DiscountModel) o;
    return Objects.equals(this.type, discountModel.type) &&
        Objects.equals(this.mode, discountModel.mode) &&
        Objects.equals(this.value, discountModel.value) &&
        Objects.equals(this.taxCode, discountModel.taxCode) &&
        Objects.equals(this.taxCodes, discountModel.taxCodes) &&
        Objects.equals(this.name, discountModel.name) &&
        Objects.equals(this.sum, discountModel.sum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, mode, value, taxCode, taxCodes, name, sum);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiscountModel {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    taxCode: ").append(toIndentedString(taxCode)).append("\n");
    sb.append("    taxCodes: ").append(toIndentedString(taxCodes)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    sum: ").append(toIndentedString(sum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
