/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DocumentsStateModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-02T14:34:29.121+02:00[Europe/Kiev]")
public class DocumentsStateModel {
  @SerializedName("last_receipt_code")
  private Integer lastReceiptCode = null;

  @SerializedName("last_report_code")
  private Integer lastReportCode = null;

  @SerializedName("last_z_report_code")
  private Integer lastZReportCode = null;

  public DocumentsStateModel lastReceiptCode(Integer lastReceiptCode) {
    this.lastReceiptCode = lastReceiptCode;
    return this;
  }

   /**
   * Get lastReceiptCode
   * @return lastReceiptCode
  **/
  @Schema(required = true, description = "")
  public Integer getLastReceiptCode() {
    return lastReceiptCode;
  }

  public void setLastReceiptCode(Integer lastReceiptCode) {
    this.lastReceiptCode = lastReceiptCode;
  }

  public DocumentsStateModel lastReportCode(Integer lastReportCode) {
    this.lastReportCode = lastReportCode;
    return this;
  }

   /**
   * Get lastReportCode
   * @return lastReportCode
  **/
  @Schema(required = true, description = "")
  public Integer getLastReportCode() {
    return lastReportCode;
  }

  public void setLastReportCode(Integer lastReportCode) {
    this.lastReportCode = lastReportCode;
  }

  public DocumentsStateModel lastZReportCode(Integer lastZReportCode) {
    this.lastZReportCode = lastZReportCode;
    return this;
  }

   /**
   * Get lastZReportCode
   * @return lastZReportCode
  **/
  @Schema(required = true, description = "")
  public Integer getLastZReportCode() {
    return lastZReportCode;
  }

  public void setLastZReportCode(Integer lastZReportCode) {
    this.lastZReportCode = lastZReportCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentsStateModel documentsStateModel = (DocumentsStateModel) o;
    return Objects.equals(this.lastReceiptCode, documentsStateModel.lastReceiptCode) &&
        Objects.equals(this.lastReportCode, documentsStateModel.lastReportCode) &&
        Objects.equals(this.lastZReportCode, documentsStateModel.lastZReportCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastReceiptCode, lastReportCode, lastZReportCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentsStateModel {\n");
    
    sb.append("    lastReceiptCode: ").append(toIndentedString(lastReceiptCode)).append("\n");
    sb.append("    lastReportCode: ").append(toIndentedString(lastReportCode)).append("\n");
    sb.append("    lastZReportCode: ").append(toIndentedString(lastZReportCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
