/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * GoodDetailsPayload
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-02T14:34:29.121+02:00[Europe/Kiev]")
public class GoodDetailsPayload {
  @SerializedName("code")
  private String code = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("barcode")
  private String barcode = null;

  @SerializedName("excise_barcode")
  private String exciseBarcode = null;

  @SerializedName("excise_barcodes")
  private List<String> exciseBarcodes = null;

  @SerializedName("header")
  private String header = null;

  @SerializedName("footer")
  private String footer = null;

  @SerializedName("price")
  private Integer price = null;

  @SerializedName("tax")
  private AnyOfGoodDetailsPayloadTax tax = null;

  @SerializedName("uktzed")
  private String uktzed = null;

  public GoodDetailsPayload code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(required = true, description = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public GoodDetailsPayload name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GoodDetailsPayload barcode(String barcode) {
    this.barcode = barcode;
    return this;
  }

   /**
   * Get barcode
   * @return barcode
  **/
  @Schema(description = "")
  public String getBarcode() {
    return barcode;
  }

  public void setBarcode(String barcode) {
    this.barcode = barcode;
  }

  public GoodDetailsPayload exciseBarcode(String exciseBarcode) {
    this.exciseBarcode = exciseBarcode;
    return this;
  }

   /**
   * Get exciseBarcode
   * @return exciseBarcode
  **/
  @Schema(description = "")
  public String getExciseBarcode() {
    return exciseBarcode;
  }

  public void setExciseBarcode(String exciseBarcode) {
    this.exciseBarcode = exciseBarcode;
  }

  public GoodDetailsPayload exciseBarcodes(List<String> exciseBarcodes) {
    this.exciseBarcodes = exciseBarcodes;
    return this;
  }

  public GoodDetailsPayload addExciseBarcodesItem(String exciseBarcodesItem) {
    if (this.exciseBarcodes == null) {
      this.exciseBarcodes = new ArrayList<String>();
    }
    this.exciseBarcodes.add(exciseBarcodesItem);
    return this;
  }

   /**
   * Get exciseBarcodes
   * @return exciseBarcodes
  **/
  @Schema(description = "")
  public List<String> getExciseBarcodes() {
    return exciseBarcodes;
  }

  public void setExciseBarcodes(List<String> exciseBarcodes) {
    this.exciseBarcodes = exciseBarcodes;
  }

  public GoodDetailsPayload header(String header) {
    this.header = header;
    return this;
  }

   /**
   * Get header
   * @return header
  **/
  @Schema(description = "")
  public String getHeader() {
    return header;
  }

  public void setHeader(String header) {
    this.header = header;
  }

  public GoodDetailsPayload footer(String footer) {
    this.footer = footer;
    return this;
  }

   /**
   * Get footer
   * @return footer
  **/
  @Schema(description = "")
  public String getFooter() {
    return footer;
  }

  public void setFooter(String footer) {
    this.footer = footer;
  }

  public GoodDetailsPayload price(Integer price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @Schema(required = true, description = "")
  public Integer getPrice() {
    return price;
  }

  public void setPrice(Integer price) {
    this.price = price;
  }

  public GoodDetailsPayload tax(AnyOfGoodDetailsPayloadTax tax) {
    this.tax = tax;
    return this;
  }

   /**
   * Get tax
   * @return tax
  **/
  @Schema(description = "")
  public AnyOfGoodDetailsPayloadTax getTax() {
    return tax;
  }

  public void setTax(AnyOfGoodDetailsPayloadTax tax) {
    this.tax = tax;
  }

  public GoodDetailsPayload uktzed(String uktzed) {
    this.uktzed = uktzed;
    return this;
  }

   /**
   * Get uktzed
   * @return uktzed
  **/
  @Schema(description = "")
  public String getUktzed() {
    return uktzed;
  }

  public void setUktzed(String uktzed) {
    this.uktzed = uktzed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoodDetailsPayload goodDetailsPayload = (GoodDetailsPayload) o;
    return Objects.equals(this.code, goodDetailsPayload.code) &&
        Objects.equals(this.name, goodDetailsPayload.name) &&
        Objects.equals(this.barcode, goodDetailsPayload.barcode) &&
        Objects.equals(this.exciseBarcode, goodDetailsPayload.exciseBarcode) &&
        Objects.equals(this.exciseBarcodes, goodDetailsPayload.exciseBarcodes) &&
        Objects.equals(this.header, goodDetailsPayload.header) &&
        Objects.equals(this.footer, goodDetailsPayload.footer) &&
        Objects.equals(this.price, goodDetailsPayload.price) &&
        Objects.equals(this.tax, goodDetailsPayload.tax) &&
        Objects.equals(this.uktzed, goodDetailsPayload.uktzed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, name, barcode, exciseBarcode, exciseBarcodes, header, footer, price, tax, uktzed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoodDetailsPayload {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    barcode: ").append(toIndentedString(barcode)).append("\n");
    sb.append("    exciseBarcode: ").append(toIndentedString(exciseBarcode)).append("\n");
    sb.append("    exciseBarcodes: ").append(toIndentedString(exciseBarcodes)).append("\n");
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    footer: ").append(toIndentedString(footer)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    tax: ").append(toIndentedString(tax)).append("\n");
    sb.append("    uktzed: ").append(toIndentedString(uktzed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
