/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.time.OffsetDateTime;
// import org.threeten.bp.OffsetDateTime;
/**
 * GoOfflinePayload
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-02T14:34:29.121+02:00[Europe/Kiev]")
public class GoOfflinePayload {
  @SerializedName("go_offline_date")
  private OffsetDateTime goOfflineDate = null;

  @SerializedName("fiscal_code")
  private String fiscalCode = null;

  public GoOfflinePayload goOfflineDate(OffsetDateTime goOfflineDate) {
    this.goOfflineDate = goOfflineDate;
    return this;
  }

   /**
   * Get goOfflineDate
   * @return goOfflineDate
  **/
  @Schema(description = "")
  public OffsetDateTime getGoOfflineDate() {
    return goOfflineDate;
  }

  public void setGoOfflineDate(OffsetDateTime goOfflineDate) {
    this.goOfflineDate = goOfflineDate;
  }

  public GoOfflinePayload fiscalCode(String fiscalCode) {
    this.fiscalCode = fiscalCode;
    return this;
  }

   /**
   * Get fiscalCode
   * @return fiscalCode
  **/
  @Schema(description = "")
  public String getFiscalCode() {
    return fiscalCode;
  }

  public void setFiscalCode(String fiscalCode) {
    this.fiscalCode = fiscalCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoOfflinePayload goOfflinePayload = (GoOfflinePayload) o;
    return Objects.equals(this.goOfflineDate, goOfflinePayload.goOfflineDate) &&
        Objects.equals(this.fiscalCode, goOfflinePayload.fiscalCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(goOfflineDate, fiscalCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoOfflinePayload {\n");
    
    sb.append("    goOfflineDate: ").append(toIndentedString(goOfflineDate)).append("\n");
    sb.append("    fiscalCode: ").append(toIndentedString(fiscalCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
