/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.v3.oas.annotations.media.Schema;
import ua.checkbox.j8client.model.DeliveryPayload;
import ua.checkbox.j8client.model.DiscountPayload;
import ua.checkbox.j8client.model.GoodItemPayload;

import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
// import org.threeten.bp.OffsetDateTime;
/**
 * OfflineReceiptSellPayload
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-02T14:34:29.121+02:00[Europe/Kiev]")
public class OfflineReceiptSellPayload {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("cashier_name")
  private String cashierName = null;

  @SerializedName("departament")
  private String departament = null;

  @SerializedName("goods")
  private List<GoodItemPayload> goods = new ArrayList<GoodItemPayload>();

  @SerializedName("delivery")
  private DeliveryPayload delivery = null;

  @SerializedName("discounts")
  private List<DiscountPayload> discounts = null;

  @SerializedName("payments")
  private List<AnyOfOfflineReceiptSellPayloadPaymentsItems> payments = null;

  @SerializedName("rounding")
  private Boolean rounding = false;

  @SerializedName("header")
  private String header = null;

  @SerializedName("footer")
  private String footer = null;

  @SerializedName("barcode")
  private String barcode = null;

  @SerializedName("order_id")
  private UUID orderId = null;

  @SerializedName("related_receipt_id")
  private UUID relatedReceiptId = null;

  @SerializedName("previous_receipt_id")
  private UUID previousReceiptId = null;

  @SerializedName("technical_return")
  private Boolean technicalReturn = false;

  @SerializedName("context")
  private Map<String, Object> context = null;

  @SerializedName("is_pawnshop")
  private Boolean isPawnshop = false;

  @SerializedName("fiscal_code")
  private String fiscalCode = null;

  @SerializedName("fiscal_date")
  private OffsetDateTime fiscalDate = null;

  public OfflineReceiptSellPayload id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public OfflineReceiptSellPayload cashierName(String cashierName) {
    this.cashierName = cashierName;
    return this;
  }

   /**
   * Get cashierName
   * @return cashierName
  **/
  @Schema(description = "")
  public String getCashierName() {
    return cashierName;
  }

  public void setCashierName(String cashierName) {
    this.cashierName = cashierName;
  }

  public OfflineReceiptSellPayload departament(String departament) {
    this.departament = departament;
    return this;
  }

   /**
   * Get departament
   * @return departament
  **/
  @Schema(description = "")
  public String getDepartament() {
    return departament;
  }

  public void setDepartament(String departament) {
    this.departament = departament;
  }

  public OfflineReceiptSellPayload goods(List<GoodItemPayload> goods) {
    this.goods = goods;
    return this;
  }

  public OfflineReceiptSellPayload addGoodsItem(GoodItemPayload goodsItem) {
    this.goods.add(goodsItem);
    return this;
  }

   /**
   * Get goods
   * @return goods
  **/
  @Schema(required = true, description = "")
  public List<GoodItemPayload> getGoods() {
    return goods;
  }

  public void setGoods(List<GoodItemPayload> goods) {
    this.goods = goods;
  }

  public OfflineReceiptSellPayload delivery(DeliveryPayload delivery) {
    this.delivery = delivery;
    return this;
  }

   /**
   * Get delivery
   * @return delivery
  **/
  @Schema(description = "")
  public DeliveryPayload getDelivery() {
    return delivery;
  }

  public void setDelivery(DeliveryPayload delivery) {
    this.delivery = delivery;
  }

  public OfflineReceiptSellPayload discounts(List<DiscountPayload> discounts) {
    this.discounts = discounts;
    return this;
  }

  public OfflineReceiptSellPayload addDiscountsItem(DiscountPayload discountsItem) {
    if (this.discounts == null) {
      this.discounts = new ArrayList<DiscountPayload>();
    }
    this.discounts.add(discountsItem);
    return this;
  }

   /**
   * Get discounts
   * @return discounts
  **/
  @Schema(description = "")
  public List<DiscountPayload> getDiscounts() {
    return discounts;
  }

  public void setDiscounts(List<DiscountPayload> discounts) {
    this.discounts = discounts;
  }

  public OfflineReceiptSellPayload payments(List<AnyOfOfflineReceiptSellPayloadPaymentsItems> payments) {
    this.payments = payments;
    return this;
  }

  public OfflineReceiptSellPayload addPaymentsItem(AnyOfOfflineReceiptSellPayloadPaymentsItems paymentsItem) {
    if (this.payments == null) {
      this.payments = new ArrayList<AnyOfOfflineReceiptSellPayloadPaymentsItems>();
    }
    this.payments.add(paymentsItem);
    return this;
  }

   /**
   * Get payments
   * @return payments
  **/
  @Schema(description = "")
  public List<AnyOfOfflineReceiptSellPayloadPaymentsItems> getPayments() {
    return payments;
  }

  public void setPayments(List<AnyOfOfflineReceiptSellPayloadPaymentsItems> payments) {
    this.payments = payments;
  }

  public OfflineReceiptSellPayload rounding(Boolean rounding) {
    this.rounding = rounding;
    return this;
  }

   /**
   * Get rounding
   * @return rounding
  **/
  @Schema(description = "")
  public Boolean isRounding() {
    return rounding;
  }

  public void setRounding(Boolean rounding) {
    this.rounding = rounding;
  }

  public OfflineReceiptSellPayload header(String header) {
    this.header = header;
    return this;
  }

   /**
   * Get header
   * @return header
  **/
  @Schema(description = "")
  public String getHeader() {
    return header;
  }

  public void setHeader(String header) {
    this.header = header;
  }

  public OfflineReceiptSellPayload footer(String footer) {
    this.footer = footer;
    return this;
  }

   /**
   * Get footer
   * @return footer
  **/
  @Schema(description = "")
  public String getFooter() {
    return footer;
  }

  public void setFooter(String footer) {
    this.footer = footer;
  }

  public OfflineReceiptSellPayload barcode(String barcode) {
    this.barcode = barcode;
    return this;
  }

   /**
   * Get barcode
   * @return barcode
  **/
  @Schema(description = "")
  public String getBarcode() {
    return barcode;
  }

  public void setBarcode(String barcode) {
    this.barcode = barcode;
  }

  public OfflineReceiptSellPayload orderId(UUID orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  @Schema(description = "")
  public UUID getOrderId() {
    return orderId;
  }

  public void setOrderId(UUID orderId) {
    this.orderId = orderId;
  }

  public OfflineReceiptSellPayload relatedReceiptId(UUID relatedReceiptId) {
    this.relatedReceiptId = relatedReceiptId;
    return this;
  }

   /**
   * Get relatedReceiptId
   * @return relatedReceiptId
  **/
  @Schema(description = "")
  public UUID getRelatedReceiptId() {
    return relatedReceiptId;
  }

  public void setRelatedReceiptId(UUID relatedReceiptId) {
    this.relatedReceiptId = relatedReceiptId;
  }

  public OfflineReceiptSellPayload previousReceiptId(UUID previousReceiptId) {
    this.previousReceiptId = previousReceiptId;
    return this;
  }

   /**
   * id попереднього фіскального чеку (використовується опціонально для контролю послідовності)
   * @return previousReceiptId
  **/
  @Schema(description = "id попереднього фіскального чеку (використовується опціонально для контролю послідовності)")
  public UUID getPreviousReceiptId() {
    return previousReceiptId;
  }

  public void setPreviousReceiptId(UUID previousReceiptId) {
    this.previousReceiptId = previousReceiptId;
  }

  public OfflineReceiptSellPayload technicalReturn(Boolean technicalReturn) {
    this.technicalReturn = technicalReturn;
    return this;
  }

   /**
   * Get technicalReturn
   * @return technicalReturn
  **/
  @Schema(description = "")
  public Boolean isTechnicalReturn() {
    return technicalReturn;
  }

  public void setTechnicalReturn(Boolean technicalReturn) {
    this.technicalReturn = technicalReturn;
  }

  public OfflineReceiptSellPayload context(Map<String, Object> context) {
    this.context = context;
    return this;
  }

  public OfflineReceiptSellPayload putContextItem(String key, Object contextItem) {
    if (this.context == null) {
      this.context = new HashMap<String, Object>();
    }
    this.context.put(key, contextItem);
    return this;
  }

   /**
   * Get context
   * @return context
  **/
  @Schema(description = "")
  public Map<String, Object> getContext() {
    return context;
  }

  public void setContext(Map<String, Object> context) {
    this.context = context;
  }

  public OfflineReceiptSellPayload isPawnshop(Boolean isPawnshop) {
    this.isPawnshop = isPawnshop;
    return this;
  }

   /**
   * Get isPawnshop
   * @return isPawnshop
  **/
  @Schema(description = "")
  public Boolean isIsPawnshop() {
    return isPawnshop;
  }

  public void setIsPawnshop(Boolean isPawnshop) {
    this.isPawnshop = isPawnshop;
  }

  public OfflineReceiptSellPayload fiscalCode(String fiscalCode) {
    this.fiscalCode = fiscalCode;
    return this;
  }

   /**
   * Get fiscalCode
   * @return fiscalCode
  **/
  @Schema(required = true, description = "")
  public String getFiscalCode() {
    return fiscalCode;
  }

  public void setFiscalCode(String fiscalCode) {
    this.fiscalCode = fiscalCode;
  }

  public OfflineReceiptSellPayload fiscalDate(OffsetDateTime fiscalDate) {
    this.fiscalDate = fiscalDate;
    return this;
  }

   /**
   * Get fiscalDate
   * @return fiscalDate
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getFiscalDate() {
    return fiscalDate;
  }

  public void setFiscalDate(OffsetDateTime fiscalDate) {
    this.fiscalDate = fiscalDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfflineReceiptSellPayload offlineReceiptSellPayload = (OfflineReceiptSellPayload) o;
    return Objects.equals(this.id, offlineReceiptSellPayload.id) &&
        Objects.equals(this.cashierName, offlineReceiptSellPayload.cashierName) &&
        Objects.equals(this.departament, offlineReceiptSellPayload.departament) &&
        Objects.equals(this.goods, offlineReceiptSellPayload.goods) &&
        Objects.equals(this.delivery, offlineReceiptSellPayload.delivery) &&
        Objects.equals(this.discounts, offlineReceiptSellPayload.discounts) &&
        Objects.equals(this.payments, offlineReceiptSellPayload.payments) &&
        Objects.equals(this.rounding, offlineReceiptSellPayload.rounding) &&
        Objects.equals(this.header, offlineReceiptSellPayload.header) &&
        Objects.equals(this.footer, offlineReceiptSellPayload.footer) &&
        Objects.equals(this.barcode, offlineReceiptSellPayload.barcode) &&
        Objects.equals(this.orderId, offlineReceiptSellPayload.orderId) &&
        Objects.equals(this.relatedReceiptId, offlineReceiptSellPayload.relatedReceiptId) &&
        Objects.equals(this.previousReceiptId, offlineReceiptSellPayload.previousReceiptId) &&
        Objects.equals(this.technicalReturn, offlineReceiptSellPayload.technicalReturn) &&
        Objects.equals(this.context, offlineReceiptSellPayload.context) &&
        Objects.equals(this.isPawnshop, offlineReceiptSellPayload.isPawnshop) &&
        Objects.equals(this.fiscalCode, offlineReceiptSellPayload.fiscalCode) &&
        Objects.equals(this.fiscalDate, offlineReceiptSellPayload.fiscalDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, cashierName, departament, goods, delivery, discounts, payments, rounding, header, footer, barcode, orderId, relatedReceiptId, previousReceiptId, technicalReturn, context, isPawnshop, fiscalCode, fiscalDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfflineReceiptSellPayload {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    cashierName: ").append(toIndentedString(cashierName)).append("\n");
    sb.append("    departament: ").append(toIndentedString(departament)).append("\n");
    sb.append("    goods: ").append(toIndentedString(goods)).append("\n");
    sb.append("    delivery: ").append(toIndentedString(delivery)).append("\n");
    sb.append("    discounts: ").append(toIndentedString(discounts)).append("\n");
    sb.append("    payments: ").append(toIndentedString(payments)).append("\n");
    sb.append("    rounding: ").append(toIndentedString(rounding)).append("\n");
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    footer: ").append(toIndentedString(footer)).append("\n");
    sb.append("    barcode: ").append(toIndentedString(barcode)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    relatedReceiptId: ").append(toIndentedString(relatedReceiptId)).append("\n");
    sb.append("    previousReceiptId: ").append(toIndentedString(previousReceiptId)).append("\n");
    sb.append("    technicalReturn: ").append(toIndentedString(technicalReturn)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    isPawnshop: ").append(toIndentedString(isPawnshop)).append("\n");
    sb.append("    fiscalCode: ").append(toIndentedString(fiscalCode)).append("\n");
    sb.append("    fiscalDate: ").append(toIndentedString(fiscalDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
