/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.v3.oas.annotations.media.Schema;
import ua.checkbox.j8client.model.ReceiptModel;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Пагінований результат
 */
@Schema(description = "Пагінований результат")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-02T14:34:29.121+02:00[Europe/Kiev]")
public class PaginatedResultReceiptModel_ {
  @SerializedName("meta")
  private AllOfPaginatedResultReceiptModelMeta meta = null;

  @SerializedName("results")
  private List<ReceiptModel> results = new ArrayList<ReceiptModel>();

  public PaginatedResultReceiptModel_ meta(AllOfPaginatedResultReceiptModelMeta meta) {
    this.meta = meta;
    return this;
  }

   /**
   * Get meta
   * @return meta
  **/
  @Schema(required = true, description = "")
  public AllOfPaginatedResultReceiptModelMeta getMeta() {
    return meta;
  }

  public void setMeta(AllOfPaginatedResultReceiptModelMeta meta) {
    this.meta = meta;
  }

  public PaginatedResultReceiptModel_ results(List<ReceiptModel> results) {
    this.results = results;
    return this;
  }

  public PaginatedResultReceiptModel_ addResultsItem(ReceiptModel resultsItem) {
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @Schema(required = true, description = "")
  public List<ReceiptModel> getResults() {
    return results;
  }

  public void setResults(List<ReceiptModel> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaginatedResultReceiptModel_ paginatedResultReceiptModel_ = (PaginatedResultReceiptModel_) o;
    return Objects.equals(this.meta, paginatedResultReceiptModel_.meta) &&
        Objects.equals(this.results, paginatedResultReceiptModel_.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(meta, results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaginatedResultReceiptModel_ {\n");
    
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
