/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.v3.oas.annotations.media.Schema;
import ua.checkbox.j8client.model.ReportPaymentsPayload;
import ua.checkbox.j8client.model.ReportTaxesPayload;

import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
// import org.threeten.bp.OffsetDateTime;
/**
 * ReportPayload
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-02T14:34:29.121+02:00[Europe/Kiev]")
public class ReportPayload {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("serial")
  private Integer serial = null;

  @SerializedName("payments")
  private List<ReportPaymentsPayload> payments = new ArrayList<ReportPaymentsPayload>();

  @SerializedName("taxes")
  private List<ReportTaxesPayload> taxes = new ArrayList<ReportTaxesPayload>();

  @SerializedName("sell_receipts_count")
  private Integer sellReceiptsCount = null;

  @SerializedName("return_receipts_count")
  private Integer returnReceiptsCount = null;

  @SerializedName("last_receipt_id")
  private UUID lastReceiptId = null;

  @SerializedName("initial")
  private Integer initial = null;

  @SerializedName("balance")
  private Integer balance = null;

  @SerializedName("sales_round_up")
  private Integer salesRoundUp = 0;

  @SerializedName("sales_round_down")
  private Integer salesRoundDown = 0;

  @SerializedName("returns_round_up")
  private Integer returnsRoundUp = 0;

  @SerializedName("returns_round_down")
  private Integer returnsRoundDown = 0;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  public ReportPayload id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public ReportPayload serial(Integer serial) {
    this.serial = serial;
    return this;
  }

   /**
   * Get serial
   * @return serial
  **/
  @Schema(description = "")
  public Integer getSerial() {
    return serial;
  }

  public void setSerial(Integer serial) {
    this.serial = serial;
  }

  public ReportPayload payments(List<ReportPaymentsPayload> payments) {
    this.payments = payments;
    return this;
  }

  public ReportPayload addPaymentsItem(ReportPaymentsPayload paymentsItem) {
    this.payments.add(paymentsItem);
    return this;
  }

   /**
   * Get payments
   * @return payments
  **/
  @Schema(required = true, description = "")
  public List<ReportPaymentsPayload> getPayments() {
    return payments;
  }

  public void setPayments(List<ReportPaymentsPayload> payments) {
    this.payments = payments;
  }

  public ReportPayload taxes(List<ReportTaxesPayload> taxes) {
    this.taxes = taxes;
    return this;
  }

  public ReportPayload addTaxesItem(ReportTaxesPayload taxesItem) {
    this.taxes.add(taxesItem);
    return this;
  }

   /**
   * Get taxes
   * @return taxes
  **/
  @Schema(required = true, description = "")
  public List<ReportTaxesPayload> getTaxes() {
    return taxes;
  }

  public void setTaxes(List<ReportTaxesPayload> taxes) {
    this.taxes = taxes;
  }

  public ReportPayload sellReceiptsCount(Integer sellReceiptsCount) {
    this.sellReceiptsCount = sellReceiptsCount;
    return this;
  }

   /**
   * Get sellReceiptsCount
   * @return sellReceiptsCount
  **/
  @Schema(required = true, description = "")
  public Integer getSellReceiptsCount() {
    return sellReceiptsCount;
  }

  public void setSellReceiptsCount(Integer sellReceiptsCount) {
    this.sellReceiptsCount = sellReceiptsCount;
  }

  public ReportPayload returnReceiptsCount(Integer returnReceiptsCount) {
    this.returnReceiptsCount = returnReceiptsCount;
    return this;
  }

   /**
   * Get returnReceiptsCount
   * @return returnReceiptsCount
  **/
  @Schema(required = true, description = "")
  public Integer getReturnReceiptsCount() {
    return returnReceiptsCount;
  }

  public void setReturnReceiptsCount(Integer returnReceiptsCount) {
    this.returnReceiptsCount = returnReceiptsCount;
  }

  public ReportPayload lastReceiptId(UUID lastReceiptId) {
    this.lastReceiptId = lastReceiptId;
    return this;
  }

   /**
   * Get lastReceiptId
   * @return lastReceiptId
  **/
  @Schema(description = "")
  public UUID getLastReceiptId() {
    return lastReceiptId;
  }

  public void setLastReceiptId(UUID lastReceiptId) {
    this.lastReceiptId = lastReceiptId;
  }

  public ReportPayload initial(Integer initial) {
    this.initial = initial;
    return this;
  }

   /**
   * Get initial
   * @return initial
  **/
  @Schema(required = true, description = "")
  public Integer getInitial() {
    return initial;
  }

  public void setInitial(Integer initial) {
    this.initial = initial;
  }

  public ReportPayload balance(Integer balance) {
    this.balance = balance;
    return this;
  }

   /**
   * Get balance
   * @return balance
  **/
  @Schema(required = true, description = "")
  public Integer getBalance() {
    return balance;
  }

  public void setBalance(Integer balance) {
    this.balance = balance;
  }

  public ReportPayload salesRoundUp(Integer salesRoundUp) {
    this.salesRoundUp = salesRoundUp;
    return this;
  }

   /**
   * Get salesRoundUp
   * @return salesRoundUp
  **/
  @Schema(description = "")
  public Integer getSalesRoundUp() {
    return salesRoundUp;
  }

  public void setSalesRoundUp(Integer salesRoundUp) {
    this.salesRoundUp = salesRoundUp;
  }

  public ReportPayload salesRoundDown(Integer salesRoundDown) {
    this.salesRoundDown = salesRoundDown;
    return this;
  }

   /**
   * Get salesRoundDown
   * @return salesRoundDown
  **/
  @Schema(description = "")
  public Integer getSalesRoundDown() {
    return salesRoundDown;
  }

  public void setSalesRoundDown(Integer salesRoundDown) {
    this.salesRoundDown = salesRoundDown;
  }

  public ReportPayload returnsRoundUp(Integer returnsRoundUp) {
    this.returnsRoundUp = returnsRoundUp;
    return this;
  }

   /**
   * Get returnsRoundUp
   * @return returnsRoundUp
  **/
  @Schema(description = "")
  public Integer getReturnsRoundUp() {
    return returnsRoundUp;
  }

  public void setReturnsRoundUp(Integer returnsRoundUp) {
    this.returnsRoundUp = returnsRoundUp;
  }

  public ReportPayload returnsRoundDown(Integer returnsRoundDown) {
    this.returnsRoundDown = returnsRoundDown;
    return this;
  }

   /**
   * Get returnsRoundDown
   * @return returnsRoundDown
  **/
  @Schema(description = "")
  public Integer getReturnsRoundDown() {
    return returnsRoundDown;
  }

  public void setReturnsRoundDown(Integer returnsRoundDown) {
    this.returnsRoundDown = returnsRoundDown;
  }

  public ReportPayload createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportPayload reportPayload = (ReportPayload) o;
    return Objects.equals(this.id, reportPayload.id) &&
        Objects.equals(this.serial, reportPayload.serial) &&
        Objects.equals(this.payments, reportPayload.payments) &&
        Objects.equals(this.taxes, reportPayload.taxes) &&
        Objects.equals(this.sellReceiptsCount, reportPayload.sellReceiptsCount) &&
        Objects.equals(this.returnReceiptsCount, reportPayload.returnReceiptsCount) &&
        Objects.equals(this.lastReceiptId, reportPayload.lastReceiptId) &&
        Objects.equals(this.initial, reportPayload.initial) &&
        Objects.equals(this.balance, reportPayload.balance) &&
        Objects.equals(this.salesRoundUp, reportPayload.salesRoundUp) &&
        Objects.equals(this.salesRoundDown, reportPayload.salesRoundDown) &&
        Objects.equals(this.returnsRoundUp, reportPayload.returnsRoundUp) &&
        Objects.equals(this.returnsRoundDown, reportPayload.returnsRoundDown) &&
        Objects.equals(this.createdAt, reportPayload.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, serial, payments, taxes, sellReceiptsCount, returnReceiptsCount, lastReceiptId, initial, balance, salesRoundUp, salesRoundDown, returnsRoundUp, returnsRoundDown, createdAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportPayload {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    serial: ").append(toIndentedString(serial)).append("\n");
    sb.append("    payments: ").append(toIndentedString(payments)).append("\n");
    sb.append("    taxes: ").append(toIndentedString(taxes)).append("\n");
    sb.append("    sellReceiptsCount: ").append(toIndentedString(sellReceiptsCount)).append("\n");
    sb.append("    returnReceiptsCount: ").append(toIndentedString(returnReceiptsCount)).append("\n");
    sb.append("    lastReceiptId: ").append(toIndentedString(lastReceiptId)).append("\n");
    sb.append("    initial: ").append(toIndentedString(initial)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    salesRoundUp: ").append(toIndentedString(salesRoundUp)).append("\n");
    sb.append("    salesRoundDown: ").append(toIndentedString(salesRoundDown)).append("\n");
    sb.append("    returnsRoundUp: ").append(toIndentedString(returnsRoundUp)).append("\n");
    sb.append("    returnsRoundDown: ").append(toIndentedString(returnsRoundDown)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
