/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
// import org.threeten.bp.OffsetDateTime;
/**
 * ReportTaxesPayload
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-02T14:34:29.121+02:00[Europe/Kiev]")
public class ReportTaxesPayload {
  @SerializedName("code")
  private Integer code = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("rate")
  private BigDecimal rate = null;

  @SerializedName("extra_rate")
  private BigDecimal extraRate = null;

  @SerializedName("sell_sum")
  private Integer sellSum = null;

  @SerializedName("return_sum")
  private Integer returnSum = null;

  @SerializedName("sales_turnover")
  private Integer salesTurnover = null;

  @SerializedName("returns_turnover")
  private Integer returnsTurnover = null;

  @SerializedName("setup_date")
  private OffsetDateTime setupDate = null;

  public ReportTaxesPayload code(Integer code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(required = true, description = "")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public ReportTaxesPayload label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @Schema(required = true, description = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public ReportTaxesPayload symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @Schema(required = true, description = "")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public ReportTaxesPayload rate(BigDecimal rate) {
    this.rate = rate;
    return this;
  }

   /**
   * Get rate
   * @return rate
  **/
  @Schema(required = true, description = "")
  public BigDecimal getRate() {
    return rate;
  }

  public void setRate(BigDecimal rate) {
    this.rate = rate;
  }

  public ReportTaxesPayload extraRate(BigDecimal extraRate) {
    this.extraRate = extraRate;
    return this;
  }

   /**
   * Get extraRate
   * @return extraRate
  **/
  @Schema(required = true, description = "")
  public BigDecimal getExtraRate() {
    return extraRate;
  }

  public void setExtraRate(BigDecimal extraRate) {
    this.extraRate = extraRate;
  }

  public ReportTaxesPayload sellSum(Integer sellSum) {
    this.sellSum = sellSum;
    return this;
  }

   /**
   * Get sellSum
   * @return sellSum
  **/
  @Schema(required = true, description = "")
  public Integer getSellSum() {
    return sellSum;
  }

  public void setSellSum(Integer sellSum) {
    this.sellSum = sellSum;
  }

  public ReportTaxesPayload returnSum(Integer returnSum) {
    this.returnSum = returnSum;
    return this;
  }

   /**
   * Get returnSum
   * @return returnSum
  **/
  @Schema(required = true, description = "")
  public Integer getReturnSum() {
    return returnSum;
  }

  public void setReturnSum(Integer returnSum) {
    this.returnSum = returnSum;
  }

  public ReportTaxesPayload salesTurnover(Integer salesTurnover) {
    this.salesTurnover = salesTurnover;
    return this;
  }

   /**
   * Get salesTurnover
   * @return salesTurnover
  **/
  @Schema(required = true, description = "")
  public Integer getSalesTurnover() {
    return salesTurnover;
  }

  public void setSalesTurnover(Integer salesTurnover) {
    this.salesTurnover = salesTurnover;
  }

  public ReportTaxesPayload returnsTurnover(Integer returnsTurnover) {
    this.returnsTurnover = returnsTurnover;
    return this;
  }

   /**
   * Get returnsTurnover
   * @return returnsTurnover
  **/
  @Schema(required = true, description = "")
  public Integer getReturnsTurnover() {
    return returnsTurnover;
  }

  public void setReturnsTurnover(Integer returnsTurnover) {
    this.returnsTurnover = returnsTurnover;
  }

  public ReportTaxesPayload setupDate(OffsetDateTime setupDate) {
    this.setupDate = setupDate;
    return this;
  }

   /**
   * Get setupDate
   * @return setupDate
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getSetupDate() {
    return setupDate;
  }

  public void setSetupDate(OffsetDateTime setupDate) {
    this.setupDate = setupDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportTaxesPayload reportTaxesPayload = (ReportTaxesPayload) o;
    return Objects.equals(this.code, reportTaxesPayload.code) &&
        Objects.equals(this.label, reportTaxesPayload.label) &&
        Objects.equals(this.symbol, reportTaxesPayload.symbol) &&
        Objects.equals(this.rate, reportTaxesPayload.rate) &&
        Objects.equals(this.extraRate, reportTaxesPayload.extraRate) &&
        Objects.equals(this.sellSum, reportTaxesPayload.sellSum) &&
        Objects.equals(this.returnSum, reportTaxesPayload.returnSum) &&
        Objects.equals(this.salesTurnover, reportTaxesPayload.salesTurnover) &&
        Objects.equals(this.returnsTurnover, reportTaxesPayload.returnsTurnover) &&
        Objects.equals(this.setupDate, reportTaxesPayload.setupDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, label, symbol, rate, extraRate, sellSum, returnSum, salesTurnover, returnsTurnover, setupDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportTaxesPayload {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    extraRate: ").append(toIndentedString(extraRate)).append("\n");
    sb.append("    sellSum: ").append(toIndentedString(sellSum)).append("\n");
    sb.append("    returnSum: ").append(toIndentedString(returnSum)).append("\n");
    sb.append("    salesTurnover: ").append(toIndentedString(salesTurnover)).append("\n");
    sb.append("    returnsTurnover: ").append(toIndentedString(returnsTurnover)).append("\n");
    sb.append("    setupDate: ").append(toIndentedString(setupDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
