/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
// import org.threeten.bp.OffsetDateTime;
/**
 * ReportTaxesModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-02T14:34:29.121+02:00[Europe/Kiev]")
public class ReportTaxesModel {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("code")
  private Integer code = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("rate")
  private BigDecimal rate = null;

  @SerializedName("sell_sum")
  private Integer sellSum = null;

  @SerializedName("return_sum")
  private Integer returnSum = null;

  @SerializedName("sales_turnover")
  private Integer salesTurnover = null;

  @SerializedName("returns_turnover")
  private Integer returnsTurnover = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  @SerializedName("setup_date")
  private OffsetDateTime setupDate = null;

  public ReportTaxesModel id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public ReportTaxesModel code(Integer code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(required = true, description = "")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public ReportTaxesModel label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @Schema(required = true, description = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public ReportTaxesModel symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @Schema(required = true, description = "")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public ReportTaxesModel rate(BigDecimal rate) {
    this.rate = rate;
    return this;
  }

   /**
   * Get rate
   * @return rate
  **/
  @Schema(required = true, description = "")
  public BigDecimal getRate() {
    return rate;
  }

  public void setRate(BigDecimal rate) {
    this.rate = rate;
  }

  public ReportTaxesModel sellSum(Integer sellSum) {
    this.sellSum = sellSum;
    return this;
  }

   /**
   * Get sellSum
   * @return sellSum
  **/
  @Schema(required = true, description = "")
  public Integer getSellSum() {
    return sellSum;
  }

  public void setSellSum(Integer sellSum) {
    this.sellSum = sellSum;
  }

  public ReportTaxesModel returnSum(Integer returnSum) {
    this.returnSum = returnSum;
    return this;
  }

   /**
   * Get returnSum
   * @return returnSum
  **/
  @Schema(required = true, description = "")
  public Integer getReturnSum() {
    return returnSum;
  }

  public void setReturnSum(Integer returnSum) {
    this.returnSum = returnSum;
  }

  public ReportTaxesModel salesTurnover(Integer salesTurnover) {
    this.salesTurnover = salesTurnover;
    return this;
  }

   /**
   * Get salesTurnover
   * @return salesTurnover
  **/
  @Schema(required = true, description = "")
  public Integer getSalesTurnover() {
    return salesTurnover;
  }

  public void setSalesTurnover(Integer salesTurnover) {
    this.salesTurnover = salesTurnover;
  }

  public ReportTaxesModel returnsTurnover(Integer returnsTurnover) {
    this.returnsTurnover = returnsTurnover;
    return this;
  }

   /**
   * Get returnsTurnover
   * @return returnsTurnover
  **/
  @Schema(required = true, description = "")
  public Integer getReturnsTurnover() {
    return returnsTurnover;
  }

  public void setReturnsTurnover(Integer returnsTurnover) {
    this.returnsTurnover = returnsTurnover;
  }

  public ReportTaxesModel createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public ReportTaxesModel setupDate(OffsetDateTime setupDate) {
    this.setupDate = setupDate;
    return this;
  }

   /**
   * Get setupDate
   * @return setupDate
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getSetupDate() {
    return setupDate;
  }

  public void setSetupDate(OffsetDateTime setupDate) {
    this.setupDate = setupDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportTaxesModel reportTaxesModel = (ReportTaxesModel) o;
    return Objects.equals(this.id, reportTaxesModel.id) &&
        Objects.equals(this.code, reportTaxesModel.code) &&
        Objects.equals(this.label, reportTaxesModel.label) &&
        Objects.equals(this.symbol, reportTaxesModel.symbol) &&
        Objects.equals(this.rate, reportTaxesModel.rate) &&
        Objects.equals(this.sellSum, reportTaxesModel.sellSum) &&
        Objects.equals(this.returnSum, reportTaxesModel.returnSum) &&
        Objects.equals(this.salesTurnover, reportTaxesModel.salesTurnover) &&
        Objects.equals(this.returnsTurnover, reportTaxesModel.returnsTurnover) &&
        Objects.equals(this.createdAt, reportTaxesModel.createdAt) &&
        Objects.equals(this.setupDate, reportTaxesModel.setupDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, code, label, symbol, rate, sellSum, returnSum, salesTurnover, returnsTurnover, createdAt, setupDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportTaxesModel {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    sellSum: ").append(toIndentedString(sellSum)).append("\n");
    sb.append("    returnSum: ").append(toIndentedString(returnSum)).append("\n");
    sb.append("    salesTurnover: ").append(toIndentedString(salesTurnover)).append("\n");
    sb.append("    returnsTurnover: ").append(toIndentedString(returnsTurnover)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    setupDate: ").append(toIndentedString(setupDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
