/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.v3.oas.annotations.media.Schema;
import ua.checkbox.j8client.model.ServiceCurrencyItemPayload;
import ua.checkbox.j8client.model.ServiceOperationType;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
/**
 * ServiceCurrencyPayload
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-02T14:34:29.121+02:00[Europe/Kiev]")
public class ServiceCurrencyPayload {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("type")
  private ServiceOperationType type = null;

  @SerializedName("currencies")
  private List<ServiceCurrencyItemPayload> currencies = new ArrayList<ServiceCurrencyItemPayload>();

  public ServiceCurrencyPayload id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public ServiceCurrencyPayload type(ServiceOperationType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(required = true, description = "")
  public ServiceOperationType getType() {
    return type;
  }

  public void setType(ServiceOperationType type) {
    this.type = type;
  }

  public ServiceCurrencyPayload currencies(List<ServiceCurrencyItemPayload> currencies) {
    this.currencies = currencies;
    return this;
  }

  public ServiceCurrencyPayload addCurrenciesItem(ServiceCurrencyItemPayload currenciesItem) {
    this.currencies.add(currenciesItem);
    return this;
  }

   /**
   * Get currencies
   * @return currencies
  **/
  @Schema(required = true, description = "")
  public List<ServiceCurrencyItemPayload> getCurrencies() {
    return currencies;
  }

  public void setCurrencies(List<ServiceCurrencyItemPayload> currencies) {
    this.currencies = currencies;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceCurrencyPayload serviceCurrencyPayload = (ServiceCurrencyPayload) o;
    return Objects.equals(this.id, serviceCurrencyPayload.id) &&
        Objects.equals(this.type, serviceCurrencyPayload.type) &&
        Objects.equals(this.currencies, serviceCurrencyPayload.currencies);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, currencies);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceCurrencyPayload {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    currencies: ").append(toIndentedString(currencies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
