/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * An enumeration.
 */
@JsonAdapter(SignatureType.Adapter.class)
public enum SignatureType {
  AGENT("AGENT"),
  UKEY("UKEY"),
  DEPOSITSIGN("DEPOSITSIGN"),
  SMARTSIGN("SMARTSIGN"),
  CLOUD_SIGNATURE("CLOUD_SIGNATURE");

  private String value;

  SignatureType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SignatureType fromValue(String text) {
    for (SignatureType b : SignatureType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<SignatureType> {
    @Override
    public void write(final JsonWriter jsonWriter, final SignatureType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SignatureType read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return SignatureType.fromValue(String.valueOf(value));
    }
  }
}
