/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * An enumeration.
 */
@JsonAdapter(TransactionType.Adapter.class)
public enum TransactionType {
  SHIFT_OPEN("SHIFT_OPEN"),
  X_REPORT("X_REPORT"),
  Z_REPORT("Z_REPORT"),
  PING("PING"),
  RECEIPT("RECEIPT"),
  LAST_RECEIPT("LAST_RECEIPT"),
  GO_OFFLINE("GO_OFFLINE"),
  ASK_OFFLINE_CODES("ASK_OFFLINE_CODES"),
  GO_ONLINE("GO_ONLINE"),
  DEL_LAST_RECEIPT("DEL_LAST_RECEIPT"),
  STATUS_RRO("STATUS_RRO"),
  INFO_RRO("INFO_RRO");

  private String value;

  TransactionType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TransactionType fromValue(String text) {
    for (TransactionType b : TransactionType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<TransactionType> {
    @Override
    public void write(final JsonWriter jsonWriter, final TransactionType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TransactionType read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return TransactionType.fromValue(String.valueOf(value));
    }
  }
}
