/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.v3.oas.annotations.media.Schema;
import ua.checkbox.j8client.model.TransactionStatus;
import ua.checkbox.j8client.model.TransactionType;

import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.UUID;
// import org.threeten.bp.OffsetDateTime;
/**
 * TransactionModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-02T14:34:29.121+02:00[Europe/Kiev]")
public class TransactionModel {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("type")
  private TransactionType type = null;

  @SerializedName("serial")
  private Integer serial = null;

  @SerializedName("status")
  private TransactionStatus status = null;

  @SerializedName("request_signed_at")
  private OffsetDateTime requestSignedAt = null;

  @SerializedName("request_received_at")
  private OffsetDateTime requestReceivedAt = null;

  @SerializedName("response_status")
  private String responseStatus = null;

  @SerializedName("response_error_message")
  private String responseErrorMessage = null;

  @SerializedName("response_id")
  private String responseId = null;

  @SerializedName("offline_id")
  private String offlineId = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  @SerializedName("updated_at")
  private OffsetDateTime updatedAt = null;

  @SerializedName("previous_hash")
  private String previousHash = null;

  @SerializedName("request_data")
  private byte[] requestData = null;

  @SerializedName("request_signature")
  private byte[] requestSignature = null;

  @SerializedName("response_id_signature")
  private byte[] responseIdSignature = null;

  @SerializedName("response_data_signature")
  private byte[] responseDataSignature = null;

  @SerializedName("response_data")
  private byte[] responseData = null;

  public TransactionModel id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public TransactionModel type(TransactionType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(required = true, description = "")
  public TransactionType getType() {
    return type;
  }

  public void setType(TransactionType type) {
    this.type = type;
  }

  public TransactionModel serial(Integer serial) {
    this.serial = serial;
    return this;
  }

   /**
   * Get serial
   * @return serial
  **/
  @Schema(required = true, description = "")
  public Integer getSerial() {
    return serial;
  }

  public void setSerial(Integer serial) {
    this.serial = serial;
  }

  public TransactionModel status(TransactionStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public TransactionStatus getStatus() {
    return status;
  }

  public void setStatus(TransactionStatus status) {
    this.status = status;
  }

  public TransactionModel requestSignedAt(OffsetDateTime requestSignedAt) {
    this.requestSignedAt = requestSignedAt;
    return this;
  }

   /**
   * Get requestSignedAt
   * @return requestSignedAt
  **/
  @Schema(description = "")
  public OffsetDateTime getRequestSignedAt() {
    return requestSignedAt;
  }

  public void setRequestSignedAt(OffsetDateTime requestSignedAt) {
    this.requestSignedAt = requestSignedAt;
  }

  public TransactionModel requestReceivedAt(OffsetDateTime requestReceivedAt) {
    this.requestReceivedAt = requestReceivedAt;
    return this;
  }

   /**
   * Get requestReceivedAt
   * @return requestReceivedAt
  **/
  @Schema(description = "")
  public OffsetDateTime getRequestReceivedAt() {
    return requestReceivedAt;
  }

  public void setRequestReceivedAt(OffsetDateTime requestReceivedAt) {
    this.requestReceivedAt = requestReceivedAt;
  }

  public TransactionModel responseStatus(String responseStatus) {
    this.responseStatus = responseStatus;
    return this;
  }

   /**
   * Get responseStatus
   * @return responseStatus
  **/
  @Schema(description = "")
  public String getResponseStatus() {
    return responseStatus;
  }

  public void setResponseStatus(String responseStatus) {
    this.responseStatus = responseStatus;
  }

  public TransactionModel responseErrorMessage(String responseErrorMessage) {
    this.responseErrorMessage = responseErrorMessage;
    return this;
  }

   /**
   * Get responseErrorMessage
   * @return responseErrorMessage
  **/
  @Schema(description = "")
  public String getResponseErrorMessage() {
    return responseErrorMessage;
  }

  public void setResponseErrorMessage(String responseErrorMessage) {
    this.responseErrorMessage = responseErrorMessage;
  }

  public TransactionModel responseId(String responseId) {
    this.responseId = responseId;
    return this;
  }

   /**
   * Get responseId
   * @return responseId
  **/
  @Schema(description = "")
  public String getResponseId() {
    return responseId;
  }

  public void setResponseId(String responseId) {
    this.responseId = responseId;
  }

  public TransactionModel offlineId(String offlineId) {
    this.offlineId = offlineId;
    return this;
  }

   /**
   * Get offlineId
   * @return offlineId
  **/
  @Schema(description = "")
  public String getOfflineId() {
    return offlineId;
  }

  public void setOfflineId(String offlineId) {
    this.offlineId = offlineId;
  }

  public TransactionModel createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public TransactionModel updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @Schema(description = "")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public TransactionModel previousHash(String previousHash) {
    this.previousHash = previousHash;
    return this;
  }

   /**
   * Get previousHash
   * @return previousHash
  **/
  @Schema(description = "")
  public String getPreviousHash() {
    return previousHash;
  }

  public void setPreviousHash(String previousHash) {
    this.previousHash = previousHash;
  }

  public TransactionModel requestData(byte[] requestData) {
    this.requestData = requestData;
    return this;
  }

   /**
   * Get requestData
   * @return requestData
  **/
  @Schema(description = "")
  public byte[] getRequestData() {
    return requestData;
  }

  public void setRequestData(byte[] requestData) {
    this.requestData = requestData;
  }

  public TransactionModel requestSignature(byte[] requestSignature) {
    this.requestSignature = requestSignature;
    return this;
  }

   /**
   * Get requestSignature
   * @return requestSignature
  **/
  @Schema(description = "")
  public byte[] getRequestSignature() {
    return requestSignature;
  }

  public void setRequestSignature(byte[] requestSignature) {
    this.requestSignature = requestSignature;
  }

  public TransactionModel responseIdSignature(byte[] responseIdSignature) {
    this.responseIdSignature = responseIdSignature;
    return this;
  }

   /**
   * Get responseIdSignature
   * @return responseIdSignature
  **/
  @Schema(description = "")
  public byte[] getResponseIdSignature() {
    return responseIdSignature;
  }

  public void setResponseIdSignature(byte[] responseIdSignature) {
    this.responseIdSignature = responseIdSignature;
  }

  public TransactionModel responseDataSignature(byte[] responseDataSignature) {
    this.responseDataSignature = responseDataSignature;
    return this;
  }

   /**
   * Get responseDataSignature
   * @return responseDataSignature
  **/
  @Schema(description = "")
  public byte[] getResponseDataSignature() {
    return responseDataSignature;
  }

  public void setResponseDataSignature(byte[] responseDataSignature) {
    this.responseDataSignature = responseDataSignature;
  }

  public TransactionModel responseData(byte[] responseData) {
    this.responseData = responseData;
    return this;
  }

   /**
   * Get responseData
   * @return responseData
  **/
  @Schema(description = "")
  public byte[] getResponseData() {
    return responseData;
  }

  public void setResponseData(byte[] responseData) {
    this.responseData = responseData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionModel transactionModel = (TransactionModel) o;
    return Objects.equals(this.id, transactionModel.id) &&
        Objects.equals(this.type, transactionModel.type) &&
        Objects.equals(this.serial, transactionModel.serial) &&
        Objects.equals(this.status, transactionModel.status) &&
        Objects.equals(this.requestSignedAt, transactionModel.requestSignedAt) &&
        Objects.equals(this.requestReceivedAt, transactionModel.requestReceivedAt) &&
        Objects.equals(this.responseStatus, transactionModel.responseStatus) &&
        Objects.equals(this.responseErrorMessage, transactionModel.responseErrorMessage) &&
        Objects.equals(this.responseId, transactionModel.responseId) &&
        Objects.equals(this.offlineId, transactionModel.offlineId) &&
        Objects.equals(this.createdAt, transactionModel.createdAt) &&
        Objects.equals(this.updatedAt, transactionModel.updatedAt) &&
        Objects.equals(this.previousHash, transactionModel.previousHash) &&
        Arrays.equals(this.requestData, transactionModel.requestData) &&
        Arrays.equals(this.requestSignature, transactionModel.requestSignature) &&
        Arrays.equals(this.responseIdSignature, transactionModel.responseIdSignature) &&
        Arrays.equals(this.responseDataSignature, transactionModel.responseDataSignature) &&
        Arrays.equals(this.responseData, transactionModel.responseData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, serial, status, requestSignedAt, requestReceivedAt, responseStatus, responseErrorMessage, responseId, offlineId, createdAt, updatedAt, previousHash, Arrays.hashCode(requestData), Arrays.hashCode(requestSignature), Arrays.hashCode(responseIdSignature), Arrays.hashCode(responseDataSignature), Arrays.hashCode(responseData));
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionModel {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    serial: ").append(toIndentedString(serial)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    requestSignedAt: ").append(toIndentedString(requestSignedAt)).append("\n");
    sb.append("    requestReceivedAt: ").append(toIndentedString(requestReceivedAt)).append("\n");
    sb.append("    responseStatus: ").append(toIndentedString(responseStatus)).append("\n");
    sb.append("    responseErrorMessage: ").append(toIndentedString(responseErrorMessage)).append("\n");
    sb.append("    responseId: ").append(toIndentedString(responseId)).append("\n");
    sb.append("    offlineId: ").append(toIndentedString(offlineId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    previousHash: ").append(toIndentedString(previousHash)).append("\n");
    sb.append("    requestData: ").append(toIndentedString(requestData)).append("\n");
    sb.append("    requestSignature: ").append(toIndentedString(requestSignature)).append("\n");
    sb.append("    responseIdSignature: ").append(toIndentedString(responseIdSignature)).append("\n");
    sb.append("    responseDataSignature: ").append(toIndentedString(responseDataSignature)).append("\n");
    sb.append("    responseData: ").append(toIndentedString(responseData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
