/*
 * test checkbox API
 * Core API of Software Registrar of Settlement Operations
 *
 * OpenAPI spec version: 0.1.26
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ua.checkbox.j8client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * UpdateTransactionPayload
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-02T14:34:29.121+02:00[Europe/Kiev]")
public class UpdateTransactionPayload {
  @SerializedName("request_signature")
  private byte[] requestSignature = null;

  public UpdateTransactionPayload requestSignature(byte[] requestSignature) {
    this.requestSignature = requestSignature;
    return this;
  }

   /**
   * Get requestSignature
   * @return requestSignature
  **/
  @Schema(required = true, description = "")
  public byte[] getRequestSignature() {
    return requestSignature;
  }

  public void setRequestSignature(byte[] requestSignature) {
    this.requestSignature = requestSignature;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateTransactionPayload updateTransactionPayload = (UpdateTransactionPayload) o;
    return Arrays.equals(this.requestSignature, updateTransactionPayload.requestSignature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Arrays.hashCode(requestSignature));
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateTransactionPayload {\n");
    
    sb.append("    requestSignature: ").append(toIndentedString(requestSignature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
